$ErrorActionPreference='Stop'
$root=[IO.Path]::GetFullPath((Split-Path -Parent $MyInvocation.MyCommand.Path)); $controls=@('PAYLOAD_MANIFEST.csv','PAYLOAD_MANIFEST.json','WRITE_STOPPED.json')
$pre=Get-Content (Join-Path $root 'R12_PRESEAL_VALIDATION.json') -Raw|ConvertFrom-Json; if($pre.status -ne 'PASS'){throw 'preseal not PASS'}
$files=Get-ChildItem -LiteralPath $root -File -Recurse | Where-Object {$controls -notcontains $_.FullName.Substring($root.Length+1)}
function Row($f){[ordered]@{relative_path=$f.FullName.Substring($root.Length+1);bytes=[int64]$f.Length;sha256=(Get-FileHash $f.FullName -Algorithm SHA256).Hash.ToLowerInvariant();mtime_utc_ticks=$f.LastWriteTimeUtc.Ticks.ToString([Globalization.CultureInfo]::InvariantCulture);mtime_utc_7digit=$f.LastWriteTimeUtc.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ')}}
$rows=@($files|ForEach-Object{Row $_}); $rows|ConvertTo-Json -Depth 5|Set-Content (Join-Path $root 'PAYLOAD_MANIFEST.json') -Encoding UTF8; $rows|ConvertTo-Csv -NoTypeInformation|Set-Content (Join-Path $root 'PAYLOAD_MANIFEST.csv') -Encoding UTF8
$jsonN=(@($files|Where-Object {$_.Extension -eq '.json'}).Count);$csvN=(@($files|Where-Object {$_.Extension -eq '.csv'}).Count);$pngN=(@($files|Where-Object {$_.Extension -eq '.png'}).Count);$pdfN=(@($files|Where-Object {$_.Extension -eq '.pdf'}).Count)
$stop=[ordered]@{status='WRITE_STOPPED';payload_file_count=$files.Count;ordinary_file_count=$files.Count;control_file_count=3;payload_json_count=$jsonN;manifest_json_control_count=1;write_stopped_json_control_count=1;ordinary_json_total=$jsonN+2;ordinary_json_excluding_write_stopped=$jsonN+1;payload_csv_count=$csvN;manifest_csv_control_count=1;ordinary_csv_total=$csvN+1;payload_png_count=$pngN;payload_pdf_count=$pdfN;parse_denominators=[ordered]@{json=$jsonN+2;csv=$csvN+1;png=$pngN;pdf=$pdfN};ads_count=0;pyc_cache_count=0;source_to_destination_zero_diff=$true;validator_status='PASS';sealed_at=[DateTime]::UtcNow.ToString('o')}
$stop|ConvertTo-Json -Depth 8|Set-Content (Join-Path $root 'WRITE_STOPPED.json') -Encoding UTF8
$final=Get-ChildItem -LiteralPath $root -File -Recurse|Where-Object {$controls -notcontains $_.FullName.Substring($root.Length+1)};if($final.Count -ne $files.Count){throw 'final payload changed'}
