Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\STRICT_R15_SA2_STATIC_FORGET_PLOT_PATCH_R115_20260828'
$source='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\worktrees\dialogue_A_visual\src\绘图源码\第01册_数学基础与统计学习基本理论\V1-C08\fig_v1_c08_coordinate.tex'
$manifest=Join-Path $root 'PAYLOAD_MANIFEST.csv';$audit=Join-Path $root 'SEAL_AUDIT.json';$marker=Join-Path $root 'WRITE_STOPPED'
$stage='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\P126_R15_STATIC_WSTOP_STAGE_20260828.tmp'
$controllerResult='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\P126_R15_STATIC_SEAL_CONTROLLER_RESULT_20260828.json'
$resultPath='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\P126_R15_STATIC_SEAL_AUDITOR_RESULT_20260828.json'
$controls=@('PAYLOAD_MANIFEST.csv','SEAL_AUDIT.json','WRITE_STOPPED')
function Sha([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256 -ErrorAction Stop).Hash.ToUpperInvariant()}
function WriteUtf8([string]$p,[string]$t){[IO.File]::WriteAllText($p,$t,[Text.UTF8Encoding]::new($false))}
function Rel([string]$p){$v=[IO.Path]::GetRelativePath($root,$p).Replace('\','/');if([string]::IsNullOrWhiteSpace($v)-or[IO.Path]::IsPathRooted($v)-or@($v.Split('/')|Where-Object{[string]::IsNullOrEmpty($_)-or$_-eq'.'-or$_-eq'..'}).Count-ne0){throw"BAD_REL:$v"};$v}
function Ads([string]$p){@((Get-Item -LiteralPath $p -Stream * -Force -ErrorAction Stop)|Where-Object{$_.Stream-ne':$DATA'}).Count}
function Snap{$rows=[Collections.Generic.List[string]]::new();foreach($f in @(Get-ChildItem -LiteralPath $root -File -Recurse -Force)){$rows.Add("F`t$(Rel $f.FullName)`t$($f.Length)`t$(Sha $f.FullName)`t$($f.CreationTimeUtc.Ticks)`t$($f.LastWriteTimeUtc.Ticks)`t$([int]$f.Attributes)")};foreach($d in @((Get-Item -LiteralPath $root -Force))+@(Get-ChildItem -LiteralPath $root -Directory -Recurse -Force)){$r=if($d.FullName-eq$root){'.'}else{Rel $d.FullName};$rows.Add("D`t$r`t0`t-`t$($d.CreationTimeUtc.Ticks)`t$($d.LastWriteTimeUtc.Ticks)`t$([int]$d.Attributes)")};$a=$rows.ToArray();[Array]::Sort($a,[StringComparer]::Ordinal);$b=[Text.UTF8Encoding]::new($false).GetBytes(([string]::Join("`n",$a))+"`n");[ordered]@{entries=$a.Count;sha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($b))}}

if(Test-Path -LiteralPath $stage){throw'STAGE_EXISTS'};if(Test-Path -LiteralPath $resultPath){throw'RESULT_EXISTS'}
$cr=Get-Content -LiteralPath $controllerResult -Raw -ErrorAction Stop|ConvertFrom-Json -Depth 10 -ErrorAction Stop;if(-not$cr.success-or$cr.invocation_count-ne1-or$cr.retry_count-ne0){throw'CONTROLLER_RESULT'}
$rows=@(Import-Csv -LiteralPath $manifest -ErrorAction Stop);if(@($rows|Group-Object -Property{[string]$_.relative_path}|Where-Object{$_.Count-ne1}).Count-ne0){throw'DUP'}
$payload=@(Get-ChildItem -LiteralPath $root -File -Recurse -Force|Where-Object{$controls-cnotcontains$_.Name});$map=[Collections.Generic.Dictionary[string,object]]::new([StringComparer]::Ordinal);foreach($f in $payload){$map.Add((Rel $f.FullName),$f)};if($map.Count-ne$rows.Count){throw'SET_COUNT'}
$mismatch=0;foreach($r in $rows){if(-not$map.ContainsKey([string]$r.relative_path)){throw"MISSING:$($r.relative_path)"};$f=$map[[string]$r.relative_path];if([long]$r.bytes-ne$f.Length-or[string]$r.sha256-cne(Sha $f.FullName)-or[long]$r.creation_time_utc_ticks-ne$f.CreationTimeUtc.Ticks-or[long]$r.last_write_time_utc_ticks-ne$f.LastWriteTimeUtc.Ticks){$mismatch++}};if($mismatch-ne0){throw'IDENTITY'}
$files=@(Get-ChildItem -LiteralPath $root -File -Recurse -Force);$dirs=@((Get-Item -LiteralPath $root -Force))+@(Get-ChildItem -LiteralPath $root -Directory -Recurse -Force);$fileRO=@($files|Where-Object{-not$_.IsReadOnly}).Count;$dirRO=@($dirs|Where-Object{($_.Attributes-band[IO.FileAttributes]::ReadOnly)-eq0}).Count;if($fileRO-ne0-or$dirRO-ne0){throw'RO'}
$mi=Get-Item -LiteralPath $marker -Force;$lines=@([IO.File]::ReadAllLines($marker,[Text.UTF8Encoding]::new($false)));$mapK=[Collections.Generic.Dictionary[string,string]]::new([StringComparer]::Ordinal);foreach($l in $lines){if($l-notmatch'^[A-Z0-9_]+=[^=].*$'){throw'BAD_LINE'};$p=$l-split'=',2;if($mapK.ContainsKey($p[0])){throw'DUP_KEY'};$mapK.Add($p[0],$p[1])};$required=@('SCHEMA','HANDOFF_ID','STATUS','ROOT','PAYLOAD_COUNT','CONTROL_COUNT','ORDINARY_COUNT','MANIFEST_SHA256','SEAL_AUDIT_SHA256','SOURCE_BEFORE_BYTES','SOURCE_BEFORE_SHA256','SOURCE_AFTER_BYTES','SOURCE_AFTER_SHA256','INCREMENTAL_DIFF_ADDITIONS','INCREMENTAL_DIFF_DELETIONS','ORDINARY_ADDPLOTS','ORDINARY_ADDPLOTS_WITH_FORGET_PLOT','MANUAL_LEGEND_IMAGES','LEGEND_ENTRIES','RENDER_VALIDATION_PENDING','TEX_BUILD_COUNT','CONTROLLER_INVOCATION','RETRY_COUNT','PREMARKER_TREE_READONLY','MARKER_LAST_WRITE_UTC_TICKS');if($mapK.Count-ne$required.Count-or@($required|Where-Object{-not$mapK.ContainsKey($_)}).Count-ne0){throw'KEY_SET'}
if($mapK['STATUS']-cne'STATIC_ONLY_NOT_RENDERED_NOT_PASS'-or[int]$mapK['PAYLOAD_COUNT']-ne$rows.Count-or[int]$mapK['ORDINARY_COUNT']-ne$files.Count-or$mapK['MANIFEST_SHA256']-cne(Sha $manifest)-or$mapK['SEAL_AUDIT_SHA256']-cne(Sha $audit)-or[long]$mapK['MARKER_LAST_WRITE_UTC_TICKS']-ne$mi.LastWriteTimeUtc.Ticks){throw'MARKER_BIND'}
$at=0;$max=[long]0;foreach($i in @($files|Where-Object{$_.FullName-ne$marker})+$dirs){if($i.LastWriteTimeUtc.Ticks-ge$mi.LastWriteTimeUtc.Ticks){$at++};if($i.LastWriteTimeUtc.Ticks-gt$max){$max=$i.LastWriteTimeUtc.Ticks}};$margin=$mi.LastWriteTimeUtc.Ticks-$max;if($at-ne0-or$margin-le0){throw'LATEST'}
$csvFail=0;foreach($f in @(Get-ChildItem -LiteralPath $root -File -Recurse -Force|Where-Object Extension -eq'.csv')){try{$null=@(Import-Csv -LiteralPath $f.FullName -ErrorAction Stop)}catch{$csvFail++}};$jsonFail=0;foreach($f in @(Get-ChildItem -LiteralPath $root -File -Recurse -Force|Where-Object Extension -eq'.json')){try{$null=Get-Content -LiteralPath $f.FullName -Raw -ErrorAction Stop|ConvertFrom-Json -Depth 30 -ErrorAction Stop}catch{$jsonFail++}};$ads=0;foreach($i in @($files+$dirs)){$ads+=Ads $i.FullName};$bad=@(Get-ChildItem -LiteralPath $root -Force -Recurse|Where-Object{$_.Name-eq'__pycache__'-or$_.Extension-in@('.pyc','.pyo')-or($_.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0}).Count;if($csvFail-ne0-or$jsonFail-ne0-or$ads-ne0-or$bad-ne0){throw'HYGIENE'}
$s1=Snap;Start-Sleep -Milliseconds 300;$s2=Snap;if($s1.sha256-ne$s2.sha256-or$s1.sha256-cne[string]$cr.snapshot_sha256){throw'POSTMARKER'};if((Get-Item -LiteralPath $source).Length-ne4686-or(Sha $source)-ne'2887758F5CC94987BE750E1EC53B555FB88CE8F71B7260CABBE0A17DDF237405'){throw'SOURCE'}
$result=[ordered]@{schema='P126_R15_STATIC_SEAL_AUDITOR_RESULT_V1';success=$true;handoff_id='A-R115-P126-SA2-STATIC-FORGET-PLOT-PATCH-20260828';status='STATIC_ONLY_NOT_RENDERED_NOT_PASS';payload_count=$rows.Count;control_count=3;ordinary_count=$files.Count;directory_count_including_root=$dirs.Count;manifest_identity_mismatch=$mismatch;file_readonly_failures=$fileRO;directory_readonly_failures=$dirRO;marker_lines=$lines.Count;marker_keys=$mapK.Count;marker_sha256=Sha $marker;strict_latest_margin_ticks=$margin;at_or_after_excluding_marker=$at;postmarker_snapshot_entries=$s1.entries;postmarker_snapshot_sha256=$s1.sha256;postmarker_drift=0;csv_parse_failures=$csvFail;json_parse_failures=$jsonFail;ads_nondefault=$ads;cache_pyc_reparse=$bad;source_identity_mismatch=0;invocation_count=1;retry_count=0}
WriteUtf8 $resultPath (($result|ConvertTo-Json -Depth 5)+"`n")
