Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$handoff='A-R116-P126-SA2-STATIC-TEXT-CURVE-COLLISION-PATCH-CONTROL-RESEAL-V2-20260828';$operation='P126_R116_R19_STATIC_EVIDENCE_ONLY_CONTROL_RESEAL_V2'
$oldRoot='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\STRICT_R19_SA2_STATIC_TEXT_CURVE_COLLISION_PATCH_R116_20260828';$destRoot='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\STRICT_R19A_SA2_STATIC_TEXT_CURVE_COLLISION_PATCH_CONTROL_RESEAL_R116_20260828'
$stage='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\P126_R19A_WRITE_STOPPED_STAGE_V2_20260828';$controllerPath='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\P126_R19A_CONTROL_RESEAL_CONTROLLER_V2_20260828.ps1';$controllerResult='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\P126_R19A_CONTROLLER_RESULT_V2_20260828.json';$auditResult='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\dialogues\A_visual\evidence\figures\FIG-P126-01\P126_R19A_AUDITOR_RESULT_V2_20260828.json'
$source='D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\worktrees\dialogue_A_visual\src\绘图源码\第01册_数学基础与统计学习基本理论\V1-C08\fig_v1_c08_coordinate.tex';$utf8=[Text.UTF8Encoding]::new($false);$strictUtf8=[Text.UTF8Encoding]::new($false,$true)
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()}
function Canon([string]$Value){if([string]::IsNullOrWhiteSpace($Value)){throw'CANON_EMPTY'};$q=$Value.Replace([string][char]92,[string][char]47);$q=$q-replace'^(?:\./)+','';if([IO.Path]::IsPathRooted($q)-or$q.StartsWith('/',[StringComparison]::Ordinal)){throw'CANON_ROOTED'};$parts=@($q.Split([char]47));if(@($parts|Where-Object{[string]::IsNullOrEmpty($_)-or$_-eq'.'-or$_-eq'..'}).Count-ne0){throw'CANON_SEGMENT'};$parts-join'/'}
function Inside([string]$Base,[string]$Relative){$baseFull=[IO.Path]::GetFullPath($Base).TrimEnd([char]92,[char]47);$native=$Relative.Replace([string][char]47,[string][char]92);$full=[IO.Path]::GetFullPath([IO.Path]::Combine($baseFull,$native));$prefix=$baseFull+[IO.Path]::DirectorySeparatorChar;if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw'PATH_ESCAPE'};$full}
function Snapshot([string]$Base){$lines=[Collections.Generic.List[string]]::new();$r=Get-Item -LiteralPath $Base -Force;$lines.Add((@('.','DIR',[int64]$r.CreationTimeUtc.Ticks,[int64]$r.LastWriteTimeUtc.Ticks,[int]$r.Attributes)-join[char]9));foreach($item in @(Get-ChildItem -LiteralPath $Base -Recurse -Force|Sort-Object FullName)){$rel=[IO.Path]::GetRelativePath($Base,$item.FullName).Replace([string][char]92,[string][char]47);if($item.PSIsContainer){$lines.Add((@($rel,'DIR',[int64]$item.CreationTimeUtc.Ticks,[int64]$item.LastWriteTimeUtc.Ticks,[int]$item.Attributes)-join[char]9))}else{$lines.Add((@($rel,[int64]$item.Length,(Sha $item.FullName),[int64]$item.CreationTimeUtc.Ticks,[int64]$item.LastWriteTimeUtc.Ticks,[int]$item.Attributes)-join[char]9))}};$bytes=$utf8.GetBytes((($lines-join"`n")+"`n"));[pscustomobject]@{entries=$lines.Count;sha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes))}}
function OrdMap([object[]]$Rows,[string]$Field){$map=[Collections.Generic.Dictionary[string,object]]::new([StringComparer]::Ordinal);foreach($row in @($Rows)){$key=Canon ([string]$row.$Field);if(-not$map.TryAdd($key,$row)){throw"DUPLICATE_$key"}};$map}
function EqualArray([object[]]$Actual,[object[]]$Expected){if($Actual.Count-ne$Expected.Count){return$false};for($i=0;$i-lt$Actual.Count;$i++){if(-not[string]::Equals([string]$Actual[$i],[string]$Expected[$i],[StringComparison]::Ordinal)){return$false}};$true}

if(Test-Path -LiteralPath $auditResult){throw'AUDIT_RESULT_EXISTS'};if(Test-Path -LiteralPath $stage){throw'STAGE_EXISTS'}
$controllerItem=Get-Item -LiteralPath $controllerPath -Force;$controllerResultItem=Get-Item -LiteralPath $controllerResult -Force;$cr=Get-Content -LiteralPath $controllerResult -Raw|ConvertFrom-Json
if(-not$cr.success-or$cr.schema-ne'P126_R19A_CONTROLLER_RESULT_V2'-or$cr.handoff_id-ne$handoff-or$cr.operation-ne$operation-or$cr.verdict-ne'STATIC_ONLY_NOT_RENDERED_NOT_PASS'-or$cr.source_root-ne$oldRoot-or$cr.destination_root-ne$destRoot-or$cr.controller_path-ne$controllerPath-or$cr.controller_bytes-ne$controllerItem.Length-or$cr.controller_sha256-ne(Sha $controllerPath)-or-not$cr.controller_readonly-or($controllerItem.Attributes-band[IO.FileAttributes]::ReadOnly)-eq0-or($controllerResultItem.Attributes-band[IO.FileAttributes]::ReadOnly)-eq0-or$cr.invocation_count-ne1-or$cr.retry_count-ne0-or-not$cr.natural_exit){throw'CONTROLLER_IDENTITY'}
if($cr.copied_count-ne9-or$cr.old_controls_copied-ne0-or$cr.payload_count-ne11-or$cr.control_count-ne3-or$cr.ordinary_count-ne14-or$cr.directory_count-ne1-or$cr.readonly_failures-ne0-or$cr.old_source_snapshot_entries-ne13-or$cr.destination_snapshot_entries-ne15-or-not$cr.stage_absent-or$cr.postmarker_drift-ne0-or$cr.postmarker_root_writes-ne0-or$cr.business_evidence_rerun){throw'CONTROLLER_COUNTS'}
$sourceItem=Get-Item -LiteralPath $source -Force;if($sourceItem.Length-ne4809-or(Sha $source)-ne'4CE06E3B00402A6C14774CC95D86348D4056B493C030CADDB9BB53DC53C6AAC2'-or$cr.source_bytes-ne4809-or$cr.source_sha256-ne(Sha $source)-or$cr.source_last_write_utc_ticks-ne$sourceItem.LastWriteTimeUtc.Ticks-or$cr.reverse_bytes-ne4686-or$cr.reverse_sha256-ne'2887758F5CC94987BE750E1EC53B555FB88CE8F71B7260CABBE0A17DDF237405'){throw'SOURCE_IDENTITY'}

$oldManifest=Join-Path $oldRoot 'PAYLOAD_MANIFEST.csv';if((Sha $oldManifest)-ne'E0155ECCD15A0E2BD0BC1FD270D8C913AD24C6A6577BF557867DE030D87EFF49'-or$cr.old_manifest_path-ne$oldManifest-or$cr.old_manifest_sha256-ne(Sha $oldManifest)){throw'OLD_MANIFEST'}
$oldRows=@(Import-Csv -LiteralPath $oldManifest);$copyPath=Join-Path $destRoot 'COPY_IDENTITY.csv';$copyRows=@(Import-Csv -LiteralPath $copyPath);$oldMap=OrdMap $oldRows 'relative_path';$copyMap=OrdMap $copyRows 'relative_path';$copyMissing=0;$copyExtra=0;$copyIdentity=0
foreach($rel in $oldMap.Keys){if(-not$copyMap.ContainsKey($rel)){$copyMissing++;continue};$o=$oldMap[$rel];$c=$copyMap[$rel];if($c.source_path-ne(Inside $oldRoot $rel)-or$c.destination_path-ne(Inside $destRoot $rel)-or[int64]$c.bytes-ne[int64]$o.bytes-or$c.sha256-ne$o.sha256-or[int64]$c.creation_time_utc_ticks-ne[int64]$o.creation_time_utc_ticks-or[int64]$c.last_write_time_utc_ticks-ne[int64]$o.last_write_time_utc_ticks){$copyIdentity++};foreach($path in @($c.source_path,$c.destination_path)){$f=Get-Item -LiteralPath $path -Force;if($f.Length-ne[int64]$o.bytes-or(Sha $path)-ne$o.sha256-or$f.CreationTimeUtc.Ticks-ne[int64]$o.creation_time_utc_ticks-or$f.LastWriteTimeUtc.Ticks-ne[int64]$o.last_write_time_utc_ticks){$copyIdentity++}}};foreach($rel in $copyMap.Keys){if(-not$oldMap.ContainsKey($rel)){$copyExtra++}}
if($oldMap.Count-ne9-or$copyMap.Count-ne9-or$copyMissing-ne0-or$copyExtra-ne0-or$copyIdentity-ne0){throw'COPY_IDENTITY'}

$provPath=Join-Path $destRoot 'COPY_PROVENANCE.json';$prov=Get-Content -LiteralPath $provPath -Raw|ConvertFrom-Json;$expectedFields=@('relative_path','bytes','sha256','creation_time_utc_ticks','last_write_time_utc_ticks')
if($prov.schema-ne'P126_R19A_COPY_PROVENANCE_V2'-or$prov.handoff_id-ne$handoff-or$prov.operation-ne$operation-or$prov.verdict-ne'STATIC_ONLY_NOT_RENDERED_NOT_PASS'-or$prov.source_root-ne$oldRoot-or$prov.destination_root-ne$destRoot-or$prov.old_manifest_path-ne$oldManifest-or$prov.old_manifest_sha256-ne(Sha $oldManifest)-or$prov.copy_identity_path-ne$copyPath-or$prov.copy_identity_sha256-ne(Sha $copyPath)-or$prov.copied_count-ne9-or$prov.old_controls_copied-ne0-or$prov.added_payload_count-ne2-or$prov.payload_count-ne11-or-not(EqualArray @($prov.preserved_fields) $expectedFields)-or$prov.source_bytes-ne4809-or$prov.source_sha256-ne(Sha $source)-or$prov.source_last_write_utc_ticks-ne$sourceItem.LastWriteTimeUtc.Ticks-or$prov.reverse_bytes-ne4686-or$prov.reverse_sha256-ne'2887758F5CC94987BE750E1EC53B555FB88CE8F71B7260CABBE0A17DDF237405'-or$prov.business_evidence_rerun){throw'PROVENANCE'}

$manifestPath=Join-Path $destRoot 'PAYLOAD_MANIFEST.csv';$manifestRows=@(Import-Csv -LiteralPath $manifestPath);$manifestMap=OrdMap $manifestRows 'relative_path';$files=@(Get-ChildItem -LiteralPath $destRoot -File -Recurse -Force);$childDirs=@(Get-ChildItem -LiteralPath $destRoot -Directory -Recurse -Force);$dirs=@($childDirs)+@((Get-Item -LiteralPath $destRoot -Force));if($files.Count-ne14-or$dirs.Count-ne1){throw'TREE_COUNTS'}
$payload=@($files|Where-Object{$_.Name-notin@('PAYLOAD_MANIFEST.csv','SEAL_AUDIT.json','WRITE_STOPPED')});$actualMap=[Collections.Generic.Dictionary[string,object]]::new([StringComparer]::Ordinal);foreach($file in $payload){$rel=Canon ([IO.Path]::GetRelativePath($destRoot,$file.FullName));if(-not$actualMap.TryAdd($rel,$file)){throw'ACTUAL_DUP'}}
$manifestMissing=0;$manifestExtra=0;$manifestIdentity=0;foreach($rel in $manifestMap.Keys){if(-not$actualMap.ContainsKey($rel)){$manifestMissing++;continue};$row=$manifestMap[$rel];$f=$actualMap[$rel];if($f.Length-ne[int64]$row.bytes-or(Sha $f.FullName)-ne$row.sha256-or$f.CreationTimeUtc.Ticks-ne[int64]$row.creation_time_utc_ticks-or$f.LastWriteTimeUtc.Ticks-ne[int64]$row.last_write_time_utc_ticks){$manifestIdentity++}};foreach($rel in $actualMap.Keys){if(-not$manifestMap.ContainsKey($rel)){$manifestExtra++}}
if($manifestMap.Count-ne11-or$actualMap.Count-ne11-or$manifestMissing-ne0-or$manifestExtra-ne0-or$manifestIdentity-ne0){throw'MANIFEST_IDENTITY'}

$sealAuditPath=Join-Path $destRoot 'SEAL_AUDIT.json';$sa=Get-Content -LiteralPath $sealAuditPath -Raw|ConvertFrom-Json
if($sa.schema-ne'P126_R19A_SEAL_AUDIT_V2'-or$sa.handoff_id-ne$handoff-or$sa.operation-ne$operation-or$sa.verdict-ne'STATIC_ONLY_NOT_RENDERED_NOT_PASS'-or$sa.source_root-ne$oldRoot-or$sa.destination_root-ne$destRoot-or$sa.old_manifest_path-ne$oldManifest-or$sa.old_manifest_sha256-ne(Sha $oldManifest)-or$sa.copied_count-ne9-or$sa.old_controls_copied-ne0-or$sa.payload_count-ne11-or$sa.control_count-ne3-or$sa.ordinary_count-ne14-or$sa.directory_count-ne1-or$sa.copy_identity_path-ne$copyPath-or$sa.copy_identity_sha256-ne(Sha $copyPath)-or$sa.copy_provenance_path-ne$provPath-or$sa.copy_provenance_sha256-ne(Sha $provPath)-or$sa.payload_manifest_path-ne$manifestPath-or$sa.payload_manifest_sha256-ne(Sha $manifestPath)-or$sa.source_bytes-ne4809-or$sa.source_sha256-ne(Sha $source)-or$sa.source_last_write_utc_ticks-ne$sourceItem.LastWriteTimeUtc.Ticks-or$sa.reverse_bytes-ne4686-or$sa.reverse_sha256-ne'2887758F5CC94987BE750E1EC53B555FB88CE8F71B7260CABBE0A17DDF237405'-or$sa.business_evidence_rerun-or$sa.error_count-ne0){throw'SEAL_AUDIT'}

$allItems=@($files)+@($dirs);$roFail=@($allItems|Where-Object{($_.Attributes-band[IO.FileAttributes]::ReadOnly)-eq0});if($roFail.Count-ne0){throw'READONLY'}
$marker=Get-Item -LiteralPath (Join-Path $destRoot 'WRITE_STOPPED') -Force;$markerBytes=[IO.File]::ReadAllBytes($marker.FullName);if($markerBytes.Length-ge3-and$markerBytes[0]-eq0xEF-and$markerBytes[1]-eq0xBB-and$markerBytes[2]-eq0xBF){throw'MARKER_BOM'};$markerText=$strictUtf8.GetString($markerBytes);$physicalParts=@([regex]::Split($markerText,"\r?\n"));if($physicalParts.Count-ne29-or$physicalParts[-1]-ne''){throw'MARKER_PHYSICAL_LINES'};$markerLines=@($physicalParts[0..27])
$expectedKeys=@('SCHEMA','HANDOFF_ID','OPERATION','VERDICT','SOURCE_ROOT','DESTINATION_ROOT','OLD_MANIFEST_SHA256','COPY_IDENTITY_SHA256','COPY_PROVENANCE_SHA256','PAYLOAD_MANIFEST_SHA256','SEAL_AUDIT_SHA256','COPIED_COUNT','OLD_CONTROLS_COPIED','PAYLOAD_COUNT','CONTROL_COUNT','ORDINARY_COUNT','DIRECTORY_COUNT','SOURCE_BYTES','SOURCE_SHA256','REVERSE_SHA256','BUSINESS_EVIDENCE_RERUN','CONTROLLER_INVOCATION_COUNT','CONTROLLER_RETRY_COUNT','AUDITOR_INVOCATION_BUDGET','SOURCE_SNAPSHOT_SHA256','POSTMARKER_WRITES','PREPARED_UTC','MARKER_LAST_WRITE_UTC_TICKS');$markerMap=[Collections.Generic.Dictionary[string,string]]::new([StringComparer]::Ordinal);$actualKeys=[Collections.Generic.List[string]]::new();$markerBad=0
foreach($line in $markerLines){if([string]::IsNullOrWhiteSpace($line)-or$line.Contains("`t")-or([regex]::Matches($line,'=')).Count-ne1-or$line-notmatch'^([A-Z0-9_]+)=([^=]+)$'-or$line-match'PLACEHOLDER|TBD|\$\{|\{\{|<[^>]+>'){$markerBad++;continue};$actualKeys.Add($Matches[1]);if(-not$markerMap.TryAdd($Matches[1],$Matches[2])){$markerBad++}}
if($markerLines.Count-ne28-or$markerMap.Count-ne28-or$markerBad-ne0-or-not(EqualArray @($actualKeys) $expectedKeys)){throw'MARKER_SCHEMA'}
$expectedValues=@('P126_R19A_WRITE_STOPPED_V2',$handoff,$operation,'STATIC_ONLY_NOT_RENDERED_NOT_PASS',$oldRoot,$destRoot,(Sha $oldManifest),(Sha $copyPath),(Sha $provPath),(Sha $manifestPath),(Sha $sealAuditPath),'9','0','11','3','14','1','4809',(Sha $source),'2887758F5CC94987BE750E1EC53B555FB88CE8F71B7260CABBE0A17DDF237405','false','1','0','1',[string]$cr.old_source_snapshot_before_sha256,'0',[string]$markerMap['PREPARED_UTC'],[string][int64]$marker.LastWriteTimeUtc.Ticks)
for($i=0;$i-lt$expectedKeys.Count;$i++){if(-not[string]::Equals($markerMap[$expectedKeys[$i]],[string]$expectedValues[$i],[StringComparison]::Ordinal)){throw"MARKER_VALUE_$($expectedKeys[$i])"}}
$parsed=[DateTime]::MinValue;if(-not[DateTime]::TryParse($markerMap['PREPARED_UTC'],[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$parsed)){throw'MARKER_PREPARED_UTC'}
$otherFiles=@($files|Where-Object FullName -ne $marker.FullName);$others=@($otherFiles)+@($dirs);$maxTicks=[int64]0;foreach($item in $others){if($item.LastWriteTimeUtc.Ticks-gt$maxTicks){$maxTicks=[int64]$item.LastWriteTimeUtc.Ticks}};$atOrAfter=@($others|Where-Object{$_.LastWriteTimeUtc.Ticks-ge$marker.LastWriteTimeUtc.Ticks});$margin=[int64]($marker.LastWriteTimeUtc.Ticks-$maxTicks)
if($atOrAfter.Count-ne0-or$margin-le0-or$cr.marker_path-ne$marker.FullName-or$cr.marker_bytes-ne$marker.Length-or$cr.marker_sha256-ne(Sha $marker.FullName)-or$cr.marker_lines-ne28-or$cr.marker_keys-ne28-or$cr.marker_ticks-ne$marker.LastWriteTimeUtc.Ticks-or$cr.strict_margin_ticks-ne$margin-or$cr.at_or_after_excluding_marker-ne0){throw'MARKER_CONTROLLER_BINDING'}
if($cr.copy_identity_path-ne$copyPath-or$cr.copy_identity_sha256-ne(Sha $copyPath)-or$cr.copy_provenance_path-ne$provPath-or$cr.copy_provenance_sha256-ne(Sha $provPath)-or$cr.payload_manifest_path-ne$manifestPath-or$cr.payload_manifest_sha256-ne(Sha $manifestPath)-or$cr.seal_audit_path-ne$sealAuditPath-or$cr.seal_audit_sha256-ne(Sha $sealAuditPath)){throw'CONTROLLER_HASH_BINDING'}

$jsonCount=0;$csvCount=0;$parseFail=0;foreach($file in $files){if($file.Extension-in@('.json','.csv')){$bytes=[IO.File]::ReadAllBytes($file.FullName);if($bytes.Length-ge3-and$bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF){$parseFail++;continue};try{$text=$strictUtf8.GetString($bytes);if($file.Extension-eq'.json'){$null=$text|ConvertFrom-Json;$jsonCount++}else{$null=@($text|ConvertFrom-Csv);$csvCount++}}catch{$parseFail++}}}
$ads=0;foreach($item in $allItems){$streams=@(Get-Item -LiteralPath $item.FullName -Stream * -Force -ErrorAction Stop);$ads+=@($streams|Where-Object Stream -ne ':$DATA').Count};$cachePyc=@($files|Where-Object{$_.Name-like'*.pyc'-or$_.FullName-match'(__pycache__|[\\/]texcache[\\/])'}).Count;$reparse=@($allItems|Where-Object{($_.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0}).Count
if($parseFail-ne0-or$ads-ne0-or$cachePyc-ne0-or$reparse-ne0){throw'HYGIENE'}

$oldNow=Snapshot $oldRoot;$destA1=Snapshot $destRoot;Start-Sleep -Milliseconds 300;$destA2=Snapshot $destRoot
if($oldNow.sha256-ne$cr.old_source_snapshot_before_sha256-or$oldNow.sha256-ne$cr.old_source_snapshot_after_copy_sha256-or$oldNow.sha256-ne$cr.old_source_snapshot_final_sha256-or$oldNow.sha256-ne$prov.source_snapshot_before_sha256-or$oldNow.sha256-ne$prov.source_snapshot_after_copy_sha256-or$oldNow.sha256-ne$sa.source_snapshot_before_sha256-or$oldNow.sha256-ne$sa.source_snapshot_after_copy_sha256-or$destA1.entries-ne15-or$destA2.entries-ne15-or$destA1.sha256-ne$destA2.sha256-or$destA1.sha256-ne$cr.destination_snapshot1_sha256-or$destA1.sha256-ne$cr.destination_snapshot2_sha256){throw'SNAPSHOT_CLOSURE'}
$out=[ordered]@{schema='P126_R19A_AUDITOR_RESULT_V2';success=$true;handoff_id=$handoff;operation=$operation;verdict='STATIC_ONLY_NOT_RENDERED_NOT_PASS';invocation_count=1;retry_count=0;copied_count=9;old_controls_copied=0;payload_count=11;control_count=3;ordinary_count=14;directory_count=$dirs.Count;copy_duplicate=0;copy_missing=$copyMissing;copy_extra=$copyExtra;copy_identity_errors=$copyIdentity;manifest_duplicate=0;manifest_missing=$manifestMissing;manifest_extra=$manifestExtra;manifest_identity_errors=$manifestIdentity;readonly_failures=$roFail.Count;marker_lines=$markerLines.Count;marker_keys=$markerMap.Count;marker_bad=$markerBad;marker_sha256=Sha $marker.FullName;strict_margin_ticks=$margin;at_or_after_excluding_marker=$atOrAfter.Count;old_snapshot_sha256=$oldNow.sha256;destination_snapshot1_sha256=$destA1.sha256;destination_snapshot2_sha256=$destA2.sha256;destination_snapshot_entries=$destA1.entries;postmarker_drift=0;json_count=$jsonCount;csv_count=$csvCount;parse_failures=$parseFail;ads_nondefault=$ads;cache_pyc=$cachePyc;reparse_points=$reparse;stage_absent=(-not(Test-Path -LiteralPath $stage));business_evidence_rerun=$false;completed_utc=[DateTime]::UtcNow.ToString('o')}
[IO.File]::WriteAllText($auditResult,($out|ConvertTo-Json -Depth 8),$utf8);[IO.File]::SetAttributes($auditResult,[IO.File]::GetAttributes($auditResult)-bor[IO.FileAttributes]::ReadOnly)
