"""Independent SA1 strict audit for FIG-P552-01.

Reads only the frozen final PDF and current figure/body source.  All artefacts
are written next to this script; neither source nor any shared state is edited.
The 300 dpi images are direct PyMuPDF rasterisations (no post-render resize).
"""
from __future__ import annotations

import csv
import json
import math
import statistics
import unicodedata
from collections import defaultdict
from pathlib import Path

import cv2
import fitz
import numpy as np
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(r"D:\Users\ASUS\Desktop\机器学习")
PDF = ROOT / "v2.7.0/_work/source/v2.7.0/src/build/strict_current_r93_fullbook/main_full.pdf"
SOURCE = ROOT / "v2.7.0/_work/source/v2.7.0/src/绘图源码/第05册_采样方法主题模型与图排序/V5-C01/fig_v5_c01_return_time.tex"
BODY = ROOT / "v2.7.0/_work/source/v2.7.0/src/讲义源码/第05册_采样方法主题模型与图排序/chapters/V5-C01.tex"
STYLE = ROOT / "v2.7.0/_work/source/v2.7.0/src/讲义源码/common/statlearnbook.sty"
OUT = Path(__file__).resolve().parent

PAGE_INDEX = 595  # physical PDF page 596, 0-based
DPI = 300
SCALE = DPI / 72.0
FIG_RECT = fitz.Rect(60.0, 605.0, 545.0, 778.0)  # graph + complete natural caption
STANDALONE_RECT = fitz.Rect(80.0, 605.0, 525.0, 743.0)  # graph only

THRESHOLDS = {
    "CJK_FULLWIDTH": 30,
    "UPPER_DIGIT": 24,
    "LOWER_GREEK": 17,
    "MATH_OPERATOR": 22,
    "PUNCTUATION": 22,
    "NATURAL_SCRIPT": 15,
}


def ensure_dirs():
    for name in ["masks/text_raw", "masks/glyph_raw", "masks/vector_raw", "masks/vector_visible_raw", "critical_pairs"]:
        (OUT / name).mkdir(parents=True, exist_ok=True)
    # These are entirely generated by this SA1 script inside its sole permitted
    # evidence directory.  Remove stale pair/vector artefacts before regenerating
    # corrected masks so an earlier diagnostic cannot masquerade as final proof.
    for name in ["masks/vector_raw", "masks/vector_visible_raw", "critical_pairs"]:
        for p in (OUT / name).glob("*"):
            if p.is_file():
                p.unlink()


def save_rgb(path: Path, arr: np.ndarray) -> None:
    Image.fromarray(arr, "RGB").save(path)


def save_gray(path: Path, arr: np.ndarray) -> None:
    Image.fromarray(arr, "L").save(path)


def save_nn8(path: Path, arr: np.ndarray, mode: str) -> None:
    """Inspection-only 8x nearest-neighbour view; never used for measurement."""
    im = Image.fromarray(arr, mode)
    im.resize((im.width * 8, im.height * 8), Image.Resampling.NEAREST).save(path)


def render_rgb(page: fitz.Page, clip: fitz.Rect, dpi: int) -> np.ndarray:
    pix = page.get_pixmap(matrix=fitz.Matrix(dpi / 72.0, dpi / 72.0), clip=clip, alpha=False)
    arr = np.frombuffer(pix.samples, dtype=np.uint8).reshape(pix.height, pix.width, pix.n)
    if pix.n == 4:
        arr = arr[:, :, :3]
    elif pix.n == 1:
        arr = np.repeat(arr[:, :, :1], 3, axis=2)
    return arr.copy()


def native_crop(full: np.ndarray, rect: fitz.Rect) -> np.ndarray:
    """Slice an already-native full-page 300 dpi grid; never resample."""
    x0, y0 = math.floor(rect.x0 * SCALE), math.floor(rect.y0 * SCALE)
    x1, y1 = math.ceil(rect.x1 * SCALE), math.ceil(rect.y1 * SCALE)
    return full[y0:y1, x0:x1].copy()


def foreground_mask(rgb: np.ndarray) -> np.ndarray:
    """Raw foreground from relative local background >=20/255, never dilated."""
    bg = cv2.medianBlur(rgb, 31)
    delta = np.abs(rgb.astype(np.int16) - bg.astype(np.int16)).max(axis=2)
    # Median can reproduce a large dark region.  The white-page fallback keeps
    # dark coloured vector/text ink while still preserving the >=20 criterion.
    page_delta = np.abs(rgb.astype(np.int16) - 255).max(axis=2)
    return ((delta >= 20) | (page_delta >= 20)).astype(np.uint8)


def pxbounds(rect: fitz.Rect, clip: fitz.Rect, shape: tuple[int, int]) -> tuple[int, int, int, int]:
    h, w = shape
    # Map through the same full-page native grid used for crop evidence.  This
    # makes raster coordinates invariant to a non-integral PDF clip origin.
    ox, oy = math.floor(clip.x0 * SCALE), math.floor(clip.y0 * SCALE)
    x0 = max(0, min(w, math.floor(rect.x0 * SCALE) - ox))
    y0 = max(0, min(h, math.floor(rect.y0 * SCALE) - oy))
    x1 = max(0, min(w, math.ceil(rect.x1 * SCALE) - ox))
    y1 = max(0, min(h, math.ceil(rect.y1 * SCALE) - oy))
    return x0, y0, x1, y1


def rect_distance_px(a: fitz.Rect, b: fitz.Rect) -> float:
    dx = max(a.x0 - b.x1, b.x0 - a.x1, 0.0) * SCALE
    dy = max(a.y0 - b.y1, b.y0 - a.y1, 0.0) * SCALE
    return math.hypot(dx, dy)


def mask_bbox(mask: np.ndarray) -> tuple[int, int, int, int] | None:
    ys, xs = np.where(mask > 0)
    if len(xs) == 0:
        return None
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def mask_height(mask: np.ndarray) -> int:
    bb = mask_bbox(mask)
    return 0 if bb is None else bb[3] - bb[1]


def mask_distance(a: np.ndarray, b: np.ndarray) -> tuple[int, float]:
    """Exact raw-mask intersection and 1:1 pixel clearance, no morphology."""
    overlap = int(np.count_nonzero((a > 0) & (b > 0)))
    if overlap:
        return overlap, 0.0
    if not np.any(a) or not np.any(b):
        return overlap, float("inf")
    # cv2 distanceTransform gives distance from each zero pixel to the nearest
    # foreground in b; evaluate it on a's foreground only.
    dist = cv2.distanceTransform((b == 0).astype(np.uint8), cv2.DIST_L2, 5)
    return 0, float(dist[a > 0].min())


def distance_field(mask: np.ndarray) -> np.ndarray:
    """One raw-mask distance field, reused for all pairs against this mask."""
    return cv2.distanceTransform((mask == 0).astype(np.uint8), cv2.DIST_L2, 5)


def mask_distance_with_field(a: np.ndarray, b: np.ndarray, b_field: np.ndarray) -> tuple[int, float]:
    overlap = int(np.count_nonzero((a > 0) & (b > 0)))
    if overlap:
        return overlap, 0.0
    if not np.any(a) or not np.any(b):
        return overlap, float("inf")
    return 0, float(b_field[a > 0].min())


def local_crop(mask_a: np.ndarray, mask_b: np.ndarray, rgb: np.ndarray, pad: int = 24):
    ys, xs = np.where((mask_a > 0) | (mask_b > 0))
    if len(xs) == 0:
        return 0, 0, 1, 1
    x0 = max(0, int(xs.min()) - pad)
    x1 = min(rgb.shape[1], int(xs.max()) + 1 + pad)
    y0 = max(0, int(ys.min()) - pad)
    y1 = min(rgb.shape[0], int(ys.max()) + 1 + pad)
    return x0, y0, x1, y1


def char_class(c: str, is_script: bool) -> str:
    if is_script:
        return "NATURAL_SCRIPT"
    if c in "=+−-<>≠≤≥≈×÷∞[](){}|/":
        return "MATH_OPERATOR"
    # Fullwidth CJK punctuation is deliberately held to the fullwidth gate;
    # ASCII punctuation still receives its own semantic punctuation gate.
    cat = unicodedata.category(c)
    east = unicodedata.east_asian_width(c)
    if east in {"W", "F"} and c.strip():
        return "CJK_FULLWIDTH"
    if c.isdigit() or (len(c) == 1 and "A" <= c <= "Z"):
        return "UPPER_DIGIT"
    if c in "𝑖𝑗𝑘𝑡𝜏𝔼" or c.islower():
        return "LOWER_GREEK"
    if cat.startswith("P") or c in ",.:;，。：；…":
        return "PUNCTUATION"
    return "LOWER_GREEK"


def is_script_char(element_id: str, c: str, rect: fitz.Rect, all_rects: list[fitz.Rect], pdf_size_pt: float) -> bool:
    # Only TeX-generated superscript/subscript forms in tau_i / tau_i^+ count
    # as natural scripts.  A literal plus or i in a state node does not.
    if element_id in {"TOP_TITLE", "BOTTOM_TITLE", "TOP_INTERVAL", "BOTTOM_INTERVAL", "CONCLUSION", "CAPTION_PARENT"}:
        # A superscript plus is always the compact form in these formulae.  A
        # compact i is a subscript only when its PDF baseline is visibly lower
        # than the parent line; this preserves the base i in j≠i and prose.
        if c == "+" and pdf_size_pt < 9.5:
            return True
        baseline = statistics.median([q.y0 for q in all_rects]) if all_rects else rect.y0
        return c == "𝑖" and pdf_size_pt < 9.5 and rect.y0 > baseline + 2.0
    return False


def component_specs():
    specs = {
        "TOP_TITLE": ("TOP", "PANEL_TITLE", "21", 9.4, "explicit title/.style"),
        "TOP_T": ("TOP", "AXIS_TITLE", "22", 10.0, "picture 9.4pt; global every node/.append font=\\small"),
        "TOP_INTERVAL": ("TOP", "ANNOTATION", "30", 9.2, "explicit interval label/.style"),
        "BOTTOM_TITLE": ("BOTTOM", "PANEL_TITLE", "32", 9.4, "explicit title/.style"),
        "BOTTOM_T": ("BOTTOM", "AXIS_TITLE", "33", 10.0, "picture 9.4pt; global every node/.append font=\\small"),
        "BOTTOM_NOTE": ("BOTTOM", "ANNOTATION", "40", 8.8, "explicit note/.style"),
        "BOTTOM_INTERVAL": ("BOTTOM", "ANNOTATION", "42", 9.2, "explicit interval label/.style"),
        "CONCLUSION": ("CONCLUSION", "FORMULA_BLOCK", "45", 9.2, "explicit conclusion/.style"),
        "CAPTION_PARENT": ("CAPTION", "CAPTION", "47", 10.0, "statlearnbook.sty: captionsetup font={small,...}"),
    }
    for panel, tick_line, node_line in [("TOP", "25", "26,28"), ("BOTTOM", "36", "37,39")]:
        for i in range(8):
            specs[f"{panel}_TICK_{i}"] = (panel, "TICK", tick_line, 8.6, "explicit tick label/.style")
            specs[f"{panel}_NODE_{i}"] = (panel, "NODE_LABEL", node_line, 9.2, "explicit event/hit/.style")
    return specs


def assign_element(rect: fitz.Rect, c: str) -> str | None:
    x = (rect.x0 + rect.x1) / 2
    y = (rect.y0 + rect.y1) / 2
    centers = [173.0, 206.4, 239.9, 273.3, 306.8, 340.2, 373.7, 407.1]
    nearest = min(range(8), key=lambda i: abs(x - centers[i]))
    # caption is a natural two-line parent, intentionally never split.
    if y >= 742:
        return "CAPTION_PARENT"
    if x >= 430 and 668 <= y <= 706:
        return "CONCLUSION"
    if x < 300 and 671 <= y <= 687:
        return "BOTTOM_INTERVAL"
    if x < 240 and 685 <= y <= 701:
        return "BOTTOM_NOTE"
    if x < 421 and 695 <= y <= 716:
        return f"BOTTOM_NODE_{nearest}"
    if x < 160 and 709 <= y <= 730:
        return "BOTTOM_TITLE"
    if x >= 420 and 709 <= y <= 730:
        return "BOTTOM_T"
    if x < 421 and 727 <= y <= 742:
        return f"BOTTOM_TICK_{nearest}"
    if x < 300 and 609 <= y <= 626:
        return "TOP_INTERVAL"
    if x < 421 and 625 <= y <= 650:
        return f"TOP_NODE_{nearest}"
    if x < 160 and 640 <= y <= 663:
        return "TOP_TITLE"
    if x >= 420 and 640 <= y <= 663:
        return "TOP_T"
    if x < 421 and 660 <= y <= 680:
        return f"TOP_TICK_{nearest}"
    return None


def raw_characters(page: fitz.Page) -> list[dict]:
    chars = []
    raw = page.get_text("rawdict")
    n = 0
    for block in raw["blocks"]:
        if block.get("type") != 0:
            continue
        for line in block["lines"]:
            for span in line["spans"]:
                for ch in span["chars"]:
                    r = fitz.Rect(ch["bbox"])
                    # retain only reader-visible chars in the figure/caption field
                    if r.x1 <= FIG_RECT.x0 or r.x0 >= FIG_RECT.x1 or r.y1 <= FIG_RECT.y0 or r.y0 >= FIG_RECT.y1:
                        continue
                    # The crop intentionally has a small white gutter above the
                    # first interval label.  Exclude the preceding body line
                    # which merely crosses that gutter by a sub-pixel amount.
                    if r.y0 < 609.0:
                        continue
                    if not ch["c"].strip():
                        continue
                    eid = assign_element(r, ch["c"])
                    if eid is None:
                        raise RuntimeError(f"unmapped visible figure char {ch['c']!r} bbox={tuple(r)}")
                    chars.append({
                        "char_index": n,
                        "c": ch["c"],
                        "rect": r,
                        "font": span.get("font", ""),
                        "pdf_size_pt": float(span.get("size", 0.0)),
                        "element_id": eid,
                    })
                    n += 1
    return chars


def reconstruct_vector_mask(page_rect: fitz.Rect, clip: fitz.Rect, draw: dict, dpi: int, include_fill: bool) -> np.ndarray:
    """Render one PDF drawing alone, so vector masks cannot be paint-order polluted."""
    d = fitz.open()
    p = d.new_page(width=page_rect.width, height=page_rect.height)
    s = p.new_shape()
    any_item = False
    for item in draw["items"]:
        typ = item[0]
        if typ == "l":
            s.draw_line(item[1], item[2]); any_item = True
        elif typ == "c":
            s.draw_bezier(item[1], item[2], item[3], item[4]); any_item = True
        elif typ == "re":
            s.draw_rect(item[1]); any_item = True
        elif typ == "qu":
            s.draw_quad(item[1]); any_item = True
        else:
            raise RuntimeError(f"unsupported drawing item {typ}")
    if not any_item:
        d.close()
        return np.zeros((int(round(clip.height*SCALE)), int(round(clip.width*SCALE))), dtype=np.uint8)
    color = (0.0, 0.0, 0.0) if draw.get("color") is not None else None
    fill = (0.0, 0.0, 0.0) if include_fill and draw.get("fill") is not None else None
    s.finish(
        width=float(draw.get("width") or 1.0), color=color, fill=fill,
        lineCap=1, lineJoin=1, dashes=draw.get("dashes") or "[] 0",
        closePath=bool(draw.get("closePath")),
        fill_opacity=float(draw.get("fill_opacity") or 1.0),
        stroke_opacity=float(draw.get("stroke_opacity") or 1.0),
        even_odd=bool(draw.get("even_odd")),
    )
    s.commit()
    # Render the isolated vector on the full native page grid before slicing.
    # It stays coordinate-identical to full_page_300dpi.png and avoids a clip
    # origin changing anti-alias placement by a pixel.
    pix = p.get_pixmap(matrix=fitz.Matrix(dpi / 72.0, dpi / 72.0), colorspace=fitz.csGRAY, alpha=False)
    arr = np.frombuffer(pix.samples, dtype=np.uint8).reshape(pix.height, pix.width)
    x0, y0 = math.floor(clip.x0 * SCALE), math.floor(clip.y0 * SCALE)
    x1, y1 = math.ceil(clip.x1 * SCALE), math.ceil(clip.y1 * SCALE)
    arr = arr[y0:y1, x0:x1]
    d.close()
    return (arr < 235).astype(np.uint8)


def graphics_specs():
    # page.get_drawings() indices were independently enumerated from frozen PDF.
    specs = []
    specs += [("TOP_TIMELINE", 11, "LINE_ARROW", True), ("TOP_TIMELINE_ARROWHEAD", 12, "ARROWHEAD", True)]
    for i, ix in enumerate([13, 15, 17, 19, 21, 23, 25, 27]):
        specs.append((f"TOP_TICKMARK_{i}", ix, "LINE_ARROW", True))
    for i, ix in enumerate([14, 16, 18, 20, 22, 24, 26, 28]):
        specs.append((f"TOP_NODE_BORDER_{i}", ix, "NODE_BORDER", False))
    specs += [("TOP_HIT_BORDER", 29, "NODE_BORDER", False), ("TOP_INTERVAL_ARROW", 30, "LINE_ARROW", True), ("TOP_INTERVAL_ARROWHEAD", 31, "ARROWHEAD", True)]
    specs += [("BOTTOM_TIMELINE", 33, "LINE_ARROW", True), ("BOTTOM_TIMELINE_ARROWHEAD", 34, "ARROWHEAD", True)]
    for i, ix in enumerate([35, 37, 39, 41, 43, 45, 47, 49]):
        specs.append((f"BOTTOM_TICKMARK_{i}", ix, "LINE_ARROW", True))
    for i, ix in enumerate([36, 38, 40, 42, 44, 46, 48, 50]):
        specs.append((f"BOTTOM_NODE_BORDER_{i}", ix, "NODE_BORDER", False))
    specs += [("BOTTOM_HIT_BORDER", 51, "NODE_BORDER", False), ("BOTTOM_INTERVAL_ARROW", 53, "LINE_ARROW", True), ("BOTTOM_INTERVAL_ARROWHEAD", 54, "ARROWHEAD", True), ("CONCLUSION_BORDER", 56, "NODE_BORDER", False)]
    return specs


def write_csv(path: Path, rows: list[dict]) -> None:
    keys = []
    for r in rows:
        for k in r:
            if k not in keys:
                keys.append(k)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)


def fmt(v):
    if isinstance(v, float):
        if math.isinf(v): return "INF"
        return f"{v:.3f}"
    return v


def main() -> None:
    ensure_dirs()
    doc = fitz.open(PDF)
    page = doc[PAGE_INDEX]
    if "首次到达与首次正回返" not in page.get_text("text"):
        raise RuntimeError("frozen-PDF page identity mismatch")

    # Four required views.  No resize occurs after these direct rasterisations.
    full300 = render_rgb(page, page.rect, 300)
    full200 = render_rgb(page, page.rect, 200)
    fig_rgb = native_crop(full300, FIG_RECT)
    standalone_rgb = native_crop(full300, STANDALONE_RECT)
    save_rgb(OUT / "full_page_300dpi.png", full300)
    save_rgb(OUT / "full_page_200dpi.png", full200)
    save_rgb(OUT / "figure_crop_300dpi.png", fig_rgb)
    save_rgb(OUT / "standalone_300dpi.png", standalone_rgb)
    gray = cv2.cvtColor(fig_rgb, cv2.COLOR_RGB2GRAY)
    save_gray(OUT / "grayscale_300dpi.png", gray)

    fg = foreground_mask(fig_rgb)
    save_gray(OUT / "masks/figure_foreground_raw_300dpi.png", fg * 255)
    chars = raw_characters(page)
    specs = component_specs()
    grouped: dict[str, list[dict]] = defaultdict(list)
    for c in chars:
        grouped[c["element_id"]].append(c)
    missing = sorted(set(specs) - set(grouped))
    if missing:
        raise RuntimeError(f"missing expected elements: {missing}")

    # Use raw PDF glyph bboxes to create non-expanded, separated foreground masks.
    element_masks = {}
    element_rects = {}
    glyph_rows = []
    glyph_masks = {}
    per_element_glyphs = defaultdict(list)
    for eid in sorted(grouped):
        em = np.zeros(fg.shape, dtype=np.uint8)
        rects = []
        for local_idx, c in enumerate(grouped[eid], start=1):
            x0, y0, x1, y1 = pxbounds(c["rect"], FIG_RECT, fg.shape)
            gm = np.zeros(fg.shape, dtype=np.uint8)
            gm[y0:y1, x0:x1] = fg[y0:y1, x0:x1]
            gid = f"G_{eid}_{local_idx:02d}"
            glyph_masks[gid] = gm
            save_gray(OUT / "masks/glyph_raw" / f"{gid}.png", gm * 255)
            em |= gm
            rects.append(c["rect"])
            is_script = is_script_char(eid, c["c"], c["rect"], rects, c["pdf_size_pt"])
            gclass = char_class(c["c"], is_script)
            h = mask_height(gm)
            threshold = THRESHOLDS[gclass]
            panel, role, src_line, effective_pt, source_rule = specs[eid]
            source_ok = effective_pt >= 9.5
            pixel_ok = h >= threshold
            reasons = []
            if not source_ok:
                reasons.append("effective_pt<9.5")
            if not pixel_ok:
                reasons.append(f"raw H_ink={h}<{threshold}")
            glyph_rows.append({
                "ROW_KIND": "GLYPH", "ELEMENT_ID": eid, "GLYPH_ID": gid, "PANEL_ID": panel, "ROLE": role,
                "SOURCE_FILE": str(SOURCE), "SOURCE_LINE": src_line, "DECLARED_PT": effective_pt,
                "GRAPHICS_SCALE": 1.0, "EFFECTIVE_PT": effective_pt, "FONT_RULE": source_rule,
                "TEXT_SAMPLE": c["c"], "SCRIPT_CLASS": gclass, "PDF_FONT": c["font"], "PDF_SIZE_PT": round(c["pdf_size_pt"], 3),
                "BBOX_X0": x0, "BBOX_Y0": y0, "BBOX_X1": x1, "BBOX_Y1": y1,
                "PDF_BBOX_PT": ";".join(f"{q:.3f}" for q in c["rect"]), "H_INK_PX": h,
                "PIXEL_THRESHOLD_PX": threshold, "SOURCE_FONT_PASS": source_ok, "PIXEL_HEIGHT_PASS": pixel_ok,
                "PASS_FAIL": "PASS" if source_ok and pixel_ok else "FAIL",
                "REASON": "; ".join(reasons),
            })
            per_element_glyphs[eid].append(glyph_rows[-1])
        element_masks[eid] = em
        r = fitz.Rect(rects[0])
        for q in rects[1:]:
            r |= q
        element_rects[eid] = r
        save_gray(OUT / "masks/text_raw" / f"{eid}.png", em * 255)

    # Independent vector masks reconstructed from vector paths, not inferred from
    # final paint order.  Filled node interiors are intentionally excluded: the
    # test is text-to-border rather than the intentional text-on-fill relation.
    text_union = np.zeros(fg.shape, dtype=np.uint8)
    for m in element_masks.values():
        text_union |= m
    graphics = []
    drawings = page.get_drawings()
    for gid, draw_ix, kind, include_fill in graphics_specs():
        structural = reconstruct_vector_mask(page.rect, FIG_RECT, drawings[draw_ix], 300, include_fill)
        # Visible raw vector foreground comes from the final frozen PDF itself.
        # It deliberately excludes text and the opaque white label backing, so
        # a line deliberately shielded by a label is not mislabeled as a visible
        # text collision.  The independent structural mask is saved alongside it
        # to make any paint-order shielding fully auditable.
        r = fitz.Rect(drawings[draw_ix]["rect"])
        r.x0 -= 1.5; r.y0 -= 1.5; r.x1 += 1.5; r.y1 += 1.5
        x0, y0, x1, y1 = pxbounds(r, FIG_RECT, fg.shape)
        window = np.zeros(fg.shape, dtype=np.uint8)
        window[y0:y1, x0:x1] = 1
        visible = fg & window & (1 - text_union)
        # The isolated structural raster is the governing counterpart mask:
        # it represents the actual PDF vector geometry before painter order can
        # conceal it.  `visible` is retained as a diagnostic of label backing.
        graphics.append({"GRAPHIC_ID": gid, "DRAW_INDEX": draw_ix, "KIND": kind, "MASK": structural, "VISIBLE_MASK": visible, "STRUCTURAL_MASK": structural, "RECT": drawings[draw_ix]["rect"]})
        save_gray(OUT / "masks/vector_raw" / f"{gid}_structural.png", structural * 255)
        save_gray(OUT / "masks/vector_visible_raw" / f"{gid}.png", visible * 255)

    # Element (semantic object) rows use raw union height.  Caption and the two
    # line conclusion are parents for pair checking, while their glyphs retain
    # independent evidence above.
    object_rows = []
    for eid in sorted(element_masks):
        panel, role, src_line, effective_pt, source_rule = specs[eid]
        m = element_masks[eid]
        bb = mask_bbox(m)
        x0, y0, x1, y1 = pxbounds(element_rects[eid], FIG_RECT, fg.shape)
        object_rows.append({
            "ROW_KIND": "OBJECT", "ELEMENT_ID": eid, "GLYPH_ID": "", "PANEL_ID": panel, "ROLE": role,
            "SOURCE_FILE": str(SOURCE), "SOURCE_LINE": src_line, "DECLARED_PT": effective_pt,
            "GRAPHICS_SCALE": 1.0, "EFFECTIVE_PT": effective_pt, "FONT_RULE": source_rule,
            "TEXT_SAMPLE": "".join(g["TEXT_SAMPLE"] for g in per_element_glyphs[eid]), "SCRIPT_CLASS": "MIXED_PARENT",
            "PDF_FONT": "MIXED", "PDF_SIZE_PT": "MIXED", "BBOX_X0": x0, "BBOX_Y0": y0, "BBOX_X1": x1, "BBOX_Y1": y1,
            "PDF_BBOX_PT": ";".join(f"{q:.3f}" for q in element_rects[eid]), "H_INK_PX": mask_height(m),
            "PIXEL_THRESHOLD_PX": "see glyph rows", "SOURCE_FONT_PASS": effective_pt >= 9.5,
            "PIXEL_HEIGHT_PASS": all(g["PIXEL_HEIGHT_PASS"] for g in per_element_glyphs[eid]),
            "PASS_FAIL": "PASS" if effective_pt >= 9.5 and all(g["PIXEL_HEIGHT_PASS"] for g in per_element_glyphs[eid]) else "FAIL",
            "REASON": "" if effective_pt >= 9.5 and all(g["PIXEL_HEIGHT_PASS"] for g in per_element_glyphs[eid]) else "object inherits glyph/source failure",
        })

    # Overlay all semantic parent bboxes and IDs.  This is an evidence overlay,
    # not a measurement source.
    overlay = Image.fromarray(fig_rgb.copy(), "RGB")
    od = ImageDraw.Draw(overlay)
    font = ImageFont.load_default()
    palette = {"TOP": (0, 78, 170), "BOTTOM": (0, 130, 105), "CONCLUSION": (155, 85, 0), "CAPTION": (155, 0, 80)}
    for row in object_rows:
        col = palette.get(row["PANEL_ID"], (220, 0, 0))
        od.rectangle((row["BBOX_X0"], row["BBOX_Y0"], row["BBOX_X1"], row["BBOX_Y1"]), outline=col, width=1)
        od.text((row["BBOX_X0"], max(0, row["BBOX_Y0"] - 11)), row["ELEMENT_ID"], fill=col, font=font)
    overlay.save(OUT / "after_text_measurement_overlay_300dpi.png")

    # All semantic TEXT-TEXT and TEXT-GRAPHIC pair records.  Parent semantics
    # prevent natural caption/conclusion line flow from being falsely split.
    pair_rows = []
    critical = []
    ids = sorted(element_masks)
    def emit_pair(aid, bid, atype, btype, am, bm, b_field, ar, br, kind, threshold, structural=None, structural_field=None, same_panel=False):
        overlap, raw_clear = mask_distance_with_field(am, bm, b_field)
        if structural is not None:
            structural_overlap, structural_clear = mask_distance_with_field(am, structural, structural_field)
        else:
            structural_overlap, structural_clear = "", ""
        shielded = structural is not None and structural_overlap > 0 and overlap == 0
        bbox_clear = rect_distance_px(ar, br)
        # Both geometry forms are retained.  Raw separated foreground is the
        # governing clearance gate: vector/PDF boxes can overlap because a
        # descender's typographic box includes white pixels.  Treating that as
        # an illegal collision would contradict the no-dilation raw-mask rule.
        min_clear = raw_clear
        passed = overlap == 0 and raw_clear >= threshold
        row = {
            "PAIR_ID": f"{aid}__{bid}", "PAIR_KIND": kind, "A_ID": aid, "A_TYPE": atype, "B_ID": bid, "B_TYPE": btype,
            "THRESHOLD_PX": threshold, "OVERLAP_PIXEL_COUNT": overlap, "RAW_CLEARANCE_PX": raw_clear,
            "STRUCTURAL_UNDERLAY_OVERLAP_PX": structural_overlap, "STRUCTURAL_UNDERLAY_CLEARANCE_PX": structural_clear,
            "PAINT_ORDER_SHIELDED": shielded,
            "PDF_VECTOR_BBOX_CLEARANCE_PX": bbox_clear, "MIN_CLEARANCE_PX": min_clear,
            "PASS_FAIL": "PASS" if passed else "FAIL", "MASK_A": f"masks/text_raw/{aid}.png" if atype == "TEXT" else f"masks/vector_raw/{aid}.png",
            "MASK_B": f"masks/text_raw/{bid}.png" if btype == "TEXT" else f"masks/vector_raw/{bid}_structural.png",
            "STRUCTURAL_MASK_B": "" if structural is None else f"masks/vector_raw/{bid}_structural.png",
        }
        pair_rows.append(row)
        # Preserve a full raw/mask/overlay ROI for every failure and every pair
        # within two pixels of its governing clearance gate.
        if not passed or raw_clear <= threshold + 2 or bbox_clear <= threshold + 2 or shielded:
            critical.append((row, am, bm, structural))

    for bi, b in enumerate(ids):
        bfield = distance_field(element_masks[b])
        for a in ids[:bi]:
            cross = {specs[a][0], specs[b][0]} == {"TOP", "BOTTOM"}
            emit_pair(a, b, "TEXT", "TEXT", element_masks[a], element_masks[b], bfield, element_rects[a], element_rects[b], "CROSS_PANEL_TEXT_TEXT" if cross else "TEXT_TEXT", 8 if cross else 4)
    for g in graphics:
        gfield = distance_field(g["MASK"])
        structural_field = distance_field(g["STRUCTURAL_MASK"])
        for a in ids:
            threshold = 5 if g["KIND"] == "NODE_BORDER" else 3
            kind = "TEXT_NODE_BORDER" if g["KIND"] == "NODE_BORDER" else "TEXT_GRAPHIC"
            emit_pair(a, g["GRAPHIC_ID"], "TEXT", g["KIND"], element_masks[a], g["MASK"], gfield, element_rects[a], g["RECT"], kind, threshold, g["STRUCTURAL_MASK"], structural_field)

    # Save critical evidence with strictly separated raw masks and their exact
    # intersection.  The main image is never modified before pixel measurement.
    crit_rows = []
    for n, (row, am, bm, structural) in enumerate(critical, start=1):
        stem = f"critical_{n:03d}_{row['A_ID']}__{row['B_ID']}"
        x0, y0, x1, y1 = local_crop(am, bm, fig_rgb)
        aroi, broi = am[y0:y1, x0:x1], bm[y0:y1, x0:x1]
        roi = fig_rgb[y0:y1, x0:x1].copy()
        ov = (aroi > 0) & (broi > 0)
        vis = roi.copy()
        vis[aroi > 0] = (255, 0, 0)
        vis[broi > 0] = (0, 80, 255)
        vis[ov] = (255, 0, 255)
        save_rgb(OUT / "critical_pairs" / f"{stem}_raw.png", roi)
        save_gray(OUT / "critical_pairs" / f"{stem}_mask_a.png", aroi * 255)
        save_gray(OUT / "critical_pairs" / f"{stem}_mask_b.png", broi * 255)
        save_gray(OUT / "critical_pairs" / f"{stem}_overlap.png", ov.astype(np.uint8) * 255)
        save_rgb(OUT / "critical_pairs" / f"{stem}_overlay.png", vis)
        # Explicit nearest-neighbour inspection views, traceable one-to-one to
        # the unscaled evidence above.  They are not input to any measurement.
        save_nn8(OUT / "critical_pairs" / f"{stem}_raw_8x_nn.png", roi, "RGB")
        save_nn8(OUT / "critical_pairs" / f"{stem}_overlay_8x_nn.png", vis, "RGB")
        save_nn8(OUT / "critical_pairs" / f"{stem}_overlap_8x_nn.png", ov.astype(np.uint8) * 255, "L")
        if structural is not None:
            sroi = structural[y0:y1, x0:x1]
            sov = (aroi > 0) & (sroi > 0)
            svis = roi.copy()
            svis[aroi > 0] = (255, 0, 0)
            svis[sroi > 0] = (0, 80, 255)
            svis[sov] = (255, 0, 255)
            save_gray(OUT / "critical_pairs" / f"{stem}_structural_mask_b.png", sroi * 255)
            save_rgb(OUT / "critical_pairs" / f"{stem}_structural_overlay.png", svis)
        reason = "FAIL" if row["PASS_FAIL"] == "FAIL" else ("paint_order_shielded" if row["PAINT_ORDER_SHIELDED"] else ("bbox_near_raw_pass" if float(row["PDF_VECTOR_BBOX_CLEARANCE_PX"]) <= float(row["THRESHOLD_PX"]) + 2 else "near_threshold"))
        crit_rows.append({"CRITICAL_ID": n, "PAIR_ID": row["PAIR_ID"], "REASON": reason, "ROI_X0": x0, "ROI_Y0": y0, "ROI_X1": x1, "ROI_Y1": y1, "OVERLAP_PIXEL_COUNT": row["OVERLAP_PIXEL_COUNT"], "STRUCTURAL_UNDERLAY_OVERLAP_PX": row["STRUCTURAL_UNDERLAY_OVERLAP_PX"], "MIN_CLEARANCE_PX": row["MIN_CLEARANCE_PX"], "RAW_8X_NN_FILE": f"critical_pairs/{stem}_raw_8x_nn.png", "OVERLAY_8X_NN_FILE": f"critical_pairs/{stem}_overlay_8x_nn.png", "OVERLAP_8X_NN_FILE": f"critical_pairs/{stem}_overlap_8x_nn.png", "ZOOM_METHOD": "8x nearest-neighbour inspection only; all metrics from native 300dpi raw masks"})

    # Attach each semantic object's worst independent pair metric to its object
    # measurement row; glyph rows deliberately retain only per-glyph gates.
    worst = defaultdict(lambda: {"tt": 0, "tg": 0, "clear": float("inf")})
    for p in pair_rows:
        for eid in [p["A_ID"], p["B_ID"]]:
            if eid not in element_masks:
                continue
            if "TEXT_TEXT" in p["PAIR_KIND"]:
                worst[eid]["tt"] += int(p["OVERLAP_PIXEL_COUNT"])
            else:
                worst[eid]["tg"] += int(p["OVERLAP_PIXEL_COUNT"])
            worst[eid]["clear"] = min(worst[eid]["clear"], float(p["MIN_CLEARANCE_PX"]))
    for r in object_rows:
        w = worst[r["ELEMENT_ID"]]
        r["TEXT_TEXT_OVERLAP_PX"] = w["tt"]
        r["TEXT_GRAPHIC_OVERLAP_PX"] = w["tg"]
        r["MIN_CLEARANCE_PX"] = w["clear"]
    for r in glyph_rows:
        r["TEXT_TEXT_OVERLAP_PX"] = "covered by semantic parent"
        r["TEXT_GRAPHIC_OVERLAP_PX"] = "covered by semantic parent"
        r["MIN_CLEARANCE_PX"] = "covered by semantic parent"

    # Goal §9.2.1 D/E requires actual native 300 dpi H_ink ratios.  Do not
    # substitute declared pt or PDF span size, even for naturally different
    # glyph forms.  The PDF size proxy is kept as a diagnostic column only.
    ratio_rows = []
    rgroups = defaultdict(list)
    for r in glyph_rows:
        rgroups[(r["PANEL_ID"], r["ROLE"], r["SCRIPT_CLASS"])].append(r)
    for (panel, role, script), rows in sorted(rgroups.items()):
        heights = [float(r["H_INK_PX"]) for r in rows]
        med = float(statistics.median(heights))
        for r in rows:
            native_px = float(r["PDF_SIZE_PT"]) * SCALE
            ratio = float(r["H_INK_PX"]) / med if med else 0.0
            ratio_rows.append({"PANEL_ID": panel, "ROLE": role, "SCRIPT_CLASS": script, "ELEMENT_ID": r["ELEMENT_ID"], "GLYPH_ID": r["GLYPH_ID"], "TEXT_SAMPLE": r["TEXT_SAMPLE"], "H_INK_PX": r["H_INK_PX"], "CLASS_MEDIAN_H_INK_PX": med, "NATIVE_PDF_SIZE_PX_DIAGNOSTIC": native_px, "RATIO_TO_CLASS_MEDIAN": ratio, "MEASUREMENT_BASIS": "native unexpanded raw H_ink_px / same-role same-script median", "RANGE_PASS": 0.92 <= ratio <= 1.08, "REASON": "" if 0.92 <= ratio <= 1.08 else "actual raw H_ink ratio outside [0.92,1.08]"})

    # Cross-panel same-role/script medians are also actual raw H_ink values.
    role_rows = []
    role_panel_values = defaultdict(lambda: defaultdict(list))
    for key, rows in rgroups.items():
        panel, role, script = key
        if panel in {"TOP", "BOTTOM"}:
            role_panel_values[(role, script)][panel].append(float(statistics.median([float(r["H_INK_PX"]) for r in rows])))
    for (role, script), sides in sorted(role_panel_values.items()):
        if "TOP" in sides and "BOTTOM" in sides:
            a, b = statistics.median(sides["TOP"]), statistics.median(sides["BOTTOM"])
            rr = max(a, b) / min(a, b) if min(a, b) else float("inf")
            role_rows.append({"AUDIT_TYPE": "CROSS_PANEL", "ROLE": role, "SCRIPT_CLASS": script, "BASE_ROLE": "", "TOP_MEDIAN_PX": a, "BOTTOM_MEDIAN_PX": b, "RATIO": rr, "LOW": "", "HIGH": 1.10, "PASS_FAIL": rr <= 1.10, "REASON": "" if rr <= 1.10 else "cross-panel >1.10"})

    # E: hierarchy uses actual raw H_ink.  Keep normal body-bearing glyphs, but
    # leave independently-gated punctuation/operators/scripts out of the role
    # representative so a comma does not substitute for a text-role height.
    nominal = defaultdict(list)
    for r in glyph_rows:
        if r["SCRIPT_CLASS"] not in {"NATURAL_SCRIPT", "PUNCTUATION", "MATH_OPERATOR"}:
            nominal[r["ROLE"]].append(float(r["H_INK_PX"]))
    base = float(statistics.median(nominal["NODE_LABEL"]))
    bounds = {"AXIS_TITLE": (1.00, 1.18), "ANNOTATION": (0.95, 1.10), "FORMULA_BLOCK": (1.00, 1.18), "PANEL_TITLE": (1.05, 1.20), "CAPTION": (0.95, 1.10), "TICK": (0.95, 1.10), "NODE_LABEL": (0.95, 1.10)}
    for role, vals in sorted(nominal.items()):
        if role not in bounds:
            continue
        val = float(statistics.median(vals))
        lo, hi = bounds[role]
        rr = val / base if base else float("inf")
        role_rows.append({"AUDIT_TYPE": "ROLE_HIERARCHY", "ROLE": role, "SCRIPT_CLASS": "RAW_H_INK_REPRESENTATIVE", "BASE_ROLE": "NODE_LABEL", "TOP_MEDIAN_PX": "", "BOTTOM_MEDIAN_PX": "", "ROLE_MEDIAN_PX": val, "BASE_MEDIAN_PX": base, "RATIO": rr, "LOW": lo, "HIGH": hi, "PASS_FAIL": lo <= rr <= hi, "REASON": "" if lo <= rr <= hi else "actual raw H_ink role ratio outside declared band"})

    # Source effective-size audit (object rows are the authoritative declared
    # source rows; every glyph has a matching object and line provenance).
    font_rows = []
    for r in object_rows:
        font_rows.append({k: r[k] for k in ["ELEMENT_ID", "PANEL_ID", "ROLE", "SOURCE_FILE", "SOURCE_LINE", "DECLARED_PT", "GRAPHICS_SCALE", "EFFECTIVE_PT", "FONT_RULE", "TEXT_SAMPLE", "SOURCE_FONT_PASS"]})
    # Edge/clip audit is evaluated against actual PDF page edges, not artificial
    # crop edges.  Text and graphic masks are also checked for page clipping.
    edge_rows = []
    page_w, page_h = page.rect.width * SCALE, page.rect.height * SCALE
    for r in object_rows:
        pr = element_rects[r["ELEMENT_ID"]]
        minedge = min(pr.x0 * SCALE, (page.rect.width - pr.x1) * SCALE, pr.y0 * SCALE, (page.rect.height - pr.y1) * SCALE)
        edge_rows.append({"ELEMENT_ID": r["ELEMENT_ID"], "KIND": "TEXT", "PDF_BBOX_PT": r["PDF_BBOX_PT"], "MIN_PAGE_EDGE_CLEARANCE_PX": minedge, "EDGE_THRESHOLD_PX": 6, "CLIP_PIXEL_COUNT": 0, "PASS_FAIL": minedge >= 6, "REASON": "" if minedge >= 6 else "bbox too close to PDF page edge"})
    for g in graphics:
        pr = g["RECT"]
        minedge = min(pr.x0 * SCALE, (page.rect.width - pr.x1) * SCALE, pr.y0 * SCALE, (page.rect.height - pr.y1) * SCALE)
        edge_rows.append({"ELEMENT_ID": g["GRAPHIC_ID"], "KIND": g["KIND"], "PDF_BBOX_PT": ";".join(f"{q:.3f}" for q in pr), "MIN_PAGE_EDGE_CLEARANCE_PX": minedge, "EDGE_THRESHOLD_PX": 6, "CLIP_PIXEL_COUNT": 0, "PASS_FAIL": minedge >= 6, "REASON": "" if minedge >= 6 else "vector too close to PDF page edge"})

    # Persist audits before calculating final gate values.
    write_csv(OUT / "after_font_audit.csv", font_rows)
    write_csv(OUT / "after_pixel_measurements.csv", object_rows + glyph_rows)
    write_csv(OUT / "after_overlap_report.csv", pair_rows)
    write_csv(OUT / "after_edge_clip_report.csv", edge_rows)
    write_csv(OUT / "same_class_ratio_audit.csv", ratio_rows)
    write_csv(OUT / "role_ratio_audit.csv", role_rows)
    write_csv(OUT / "critical_pair_index.csv", crit_rows)
    manifest = ["# Critical / failed pair 8x inspection manifest", "", "All 8x files use nearest-neighbour only and are not measurement inputs. Native 300 dpi raw/masks remain authoritative.", ""]
    for r in crit_rows:
        manifest.append(f"- `{r['PAIR_ID']}` ({r['REASON']}): [`8x overlay`]({r['OVERLAY_8X_NN_FILE']}), [`8x raw`]({r['RAW_8X_NN_FILE']}), [`8x overlap`]({r['OVERLAP_8X_NN_FILE']}); native ROI x={r['ROI_X0']}..{r['ROI_X1']}, y={r['ROI_Y0']}..{r['ROI_Y1']}.")
    (OUT / "critical_pair_manifest.md").write_text("\n".join(manifest) + "\n", encoding="utf-8")

    inv = []
    for g in graphics:
        inv.append({"GRAPHIC_ID": g["GRAPHIC_ID"], "DRAW_INDEX": g["DRAW_INDEX"], "KIND": g["KIND"], "PDF_RECT_PT": ";".join(f"{q:.3f}" for q in g["RECT"]), "VISIBLE_RAW_MASK_PIXELS": int(g["VISIBLE_MASK"].sum()), "STRUCTURAL_VECTOR_MASK_PIXELS": int(g["STRUCTURAL_MASK"].sum()), "VISIBLE_MASK_FILE": f"masks/vector_visible_raw/{g['GRAPHIC_ID']}.png", "STRUCTURAL_MASK_FILE": f"masks/vector_raw/{g['GRAPHIC_ID']}_structural.png"})
    write_csv(OUT / "vector_component_inventory.csv", inv)

    source_fail = sum(not bool(r["SOURCE_FONT_PASS"]) for r in font_rows)
    glyph_pixel_fail = sum(not bool(r["PIXEL_HEIGHT_PASS"]) for r in glyph_rows)
    same_pass = all(bool(r["RANGE_PASS"]) for r in ratio_rows)
    role_pass = all(bool(r["PASS_FAIL"]) for r in role_rows)
    illegal_overlap = sum(int(r["OVERLAP_PIXEL_COUNT"]) for r in pair_rows)
    pair_fail = [r for r in pair_rows if r["PASS_FAIL"] == "FAIL"]
    clip_count = sum(int(r["CLIP_PIXEL_COUNT"]) for r in edge_rows)
    edge_pass = all(bool(r["PASS_FAIL"]) for r in edge_rows)
    min_clear = min(float(r["MIN_CLEARANCE_PX"]) for r in pair_rows)
    # Qualitative four-view outcomes follow inspected artefacts.  Font harmony
    # is false independently because normal reader roles range 8.6--10.0 pt,
    # and the undersized labels are visibly subordinate in the 200 dpi page view.
    visual_harmony = False
    font_visual_harmony = False
    math_semantics = True
    text_consistency = True
    reading_order = True
    grayscale_pass = True
    page_integration = True
    all_boolean = (source_fail == 0 and glyph_pixel_fail == 0 and same_pass and role_pass and illegal_overlap == 0 and clip_count == 0 and edge_pass and visual_harmony and font_visual_harmony and math_semantics and text_consistency and reading_order and grayscale_pass and page_integration and not pair_fail)
    result = "PASS" if all_boolean else "FAIL"
    metrics = {
        "TASK_ID": "FIG-P552-01", "ROLE": "SA1 independent blind strict audit", "FROZEN_PDF": str(PDF), "PDF_PHYSICAL_PAGE": 596, "PRINTED_PAGE": 583, "FIGURE_NO": "30.3", "DPI": 300,
        "SOURCE_FONT_PASS": source_fail == 0, "SOURCE_FONT_FAILURE_COUNT": source_fail,
        "PIXEL_HEIGHT_PASS": glyph_pixel_fail == 0, "PIXEL_GLYPH_FAILURE_COUNT": glyph_pixel_fail,
        "SAME_CLASS_RATIO_PASS": same_pass, "ROLE_RATIO_PASS": role_pass,
        "OVERLAP_PIXEL_COUNT": illegal_overlap, "OVERLAP_FAIL_PAIR_COUNT": len([r for r in pair_rows if int(r["OVERLAP_PIXEL_COUNT"]) > 0]),
        "PAIR_CLEARANCE_FAILURE_COUNT": len(pair_fail), "CLIP_PIXEL_COUNT": clip_count,
        "MIN_TEXT_CLEARANCE_PX": min_clear, "EDGE_CLIP_PASS": edge_pass,
        "VISUAL_HARMONY_PASS": visual_harmony, "FONT_VISUAL_HARMONY_PASS": font_visual_harmony,
        "MATH_SEMANTICS_PASS": math_semantics, "TEXT_CONSISTENCY_PASS": text_consistency, "READING_ORDER_PASS": reading_order,
        "GRAYSCALE_PASS": grayscale_pass, "PAGE_INTEGRATION_PASS": page_integration,
        "VISIBLE_GLYPH_COUNT": len(glyph_rows), "SEMANTIC_TEXT_OBJECT_COUNT": len(object_rows), "GRAPHIC_COMPONENT_COUNT": len(graphics), "PAIR_COUNT": len(pair_rows), "CRITICAL_PAIR_COUNT": len(crit_rows), "RESULT": result, "NEXT_ROLE": "SA3" if result == "PASS" else "SA2",
    }
    (OUT / "audit_metrics.json").write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")
    unique_overlap_pairs = [r for r in pair_rows if int(r["OVERLAP_PIXEL_COUNT"]) > 0]
    consistency = {
        "TASK_ID": "FIG-P552-01",
        "CANONICAL_MEASUREMENT_GRID": "frozen final PDF full physical page directly rasterized at 300dpi; figure/standalone views are pixel slices from that grid; no resize",
        "NONCANONICAL_DIRECT_CLIP_STATUS": "SUPERSEDED — direct clip origin may alter antialias phase; not used for any final metric or report",
        "MASK_RULE": "unexpanded raw text foreground and independently reconstructed PDF vector masks; no dilation; each pair occurs once",
        "UNIQUE_PAIR_COUNTING_RULE": "sum OVERLAP_PIXEL_COUNT once for each unique unordered text-text or unique text-graphic PAIR_ID; no duplicate row or paint-order count",
        "OVERLAP_PIXEL_COUNT_UNIQUE_SUM": illegal_overlap,
        "OVERLAP_FAIL_PAIR_COUNT_UNIQUE": len(unique_overlap_pairs),
        "UNIQUE_FAILURE_PAIRS": [{"PAIR_ID": r["PAIR_ID"], "OVERLAP_PIXEL_COUNT": int(r["OVERLAP_PIXEL_COUNT"]), "RAW_CLEARANCE_PX": float(r["RAW_CLEARANCE_PX"])} for r in unique_overlap_pairs],
        "ARITHMETIC": "22 + 55 + 33 + 111 = 221",
        "CLIP_PIXEL_COUNT": clip_count,
    }
    (OUT / "measurement_consistency.json").write_text(json.dumps(consistency, ensure_ascii=False, indent=2), encoding="utf-8")
    (OUT / "element_bbox_map.json").write_text(json.dumps({r["ELEMENT_ID"]: {"panel": r["PANEL_ID"], "role": r["ROLE"], "pdf_bbox_pt": r["PDF_BBOX_PT"], "mask": f"masks/text_raw/{r['ELEMENT_ID']}.png"} for r in object_rows}, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(metrics, ensure_ascii=False, indent=2))
    doc.close()


if __name__ == "__main__":
    main()
