"""Plan and verify removal of only superseded self-generated R1 artifacts.

Deletion is intentionally not implemented here.  `--plan` writes a hash-bound
target list and a PowerShell file with one literal-path Remove-Item command per
file.  The caller must execute that exact script in one session, then use
`--verify`.  Nothing outside this dedicated evidence directory can qualify.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


OUT = Path(r"D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\evidence\figures\FIG-P608-01\STRICT_R1_SA1_REQUAL_R97_20260824")
CANONICAL_OUT = r"D:\Users\ASUS\Desktop\机器学习\v2.7.0\_work\evidence\figures\FIG-P608-01\STRICT_R1_SA1_REQUAL_R97_20260824"
TARGETS_CSV = OUT / "cleanup_targets_before_delete.csv"
REPORT = OUT / "CLEANUP_STALE_SELF_GENERATED.md"
PS1 = OUT / "CLEANUP_EXECUTED_EXACT.ps1"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest().upper()


def load(path: Path):
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def inside(path: Path) -> bool:
    try:
        path.resolve().relative_to(OUT.resolve())
        return True
    except ValueError:
        return False


def expected_files() -> set[Path]:
    expected: set[Path] = set()
    for r in load(OUT / "glyph_ledger.csv"):
        expected.add(OUT / r["card"])
    for r in load(OUT / "after_overlap_report.csv"):
        if r.get("evidence_card"):
            expected.add(OUT / r["evidence_card"])
    for r in load(OUT / "low_profile_calibration.csv"):
        expected.add(OUT / r["calibration_source"])
        expected.add(OUT / r["calibration_native"])
        for rel in json.loads(r["calibration_cards"]).values():
            expected.add(OUT / rel)
        calibration_id = r["calibration_id"]
        root = OUT / "low_profile_calibration"
        for suffix in (".aux", ".log", ".pdf", "_xelatex.stdout.txt"):
            expected.add(root / f"{calibration_id}{suffix}")
    return {p.resolve() for p in expected}


def plan_targets():
    expected = expected_files()
    candidates = []
    for subdir, reason in (
        (OUT / "glyph_cards", "superseded glyph card not referenced by final glyph_ledger.csv"),
        (OUT / "pair_cards", "superseded pair card not referenced by final after_overlap_report.csv"),
        (OUT / "low_profile_calibration", "superseded standalone calibration asset not referenced by final low_profile_calibration.csv"),
        (OUT / "__pycache__", "Python bytecode generated by this R1 audit session; not evidence"),
    ):
        if not subdir.exists():
            continue
        for path in sorted(p for p in subdir.iterdir() if p.is_file()):
            if path.resolve() in expected:
                continue
            if not inside(path):
                raise RuntimeError(f"refusing non-R1 target {path}")
            stat = path.stat()
            candidates.append({
                "relative_path": path.relative_to(OUT).as_posix(),
                "absolute_path": str(path),
                "bytes": stat.st_size,
                "last_write_local": datetime.fromtimestamp(stat.st_mtime).isoformat(timespec="seconds"),
                "sha256_before_delete": sha256(path),
                "reason": reason,
            })
    return candidates


def write_plan(candidates):
    fields = ["relative_path", "absolute_path", "bytes", "last_write_local", "sha256_before_delete", "reason"]
    with TARGETS_CSV.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader(); w.writerows(candidates)
    ps_lines = [
        "# Exact, literal-path cleanup for self-generated superseded R1 artifacts only.",
        "# Generated from cleanup_targets_before_delete.csv before deletion.",
        "$ErrorActionPreference = 'Stop'",
    ]
    for r in candidates:
        quoted = r["absolute_path"].replace("'", "''")
        ps_lines.append(f"Remove-Item -LiteralPath '{quoted}' -Force")
    # Windows PowerShell 5.1 reads a BOM-less UTF-8 script as the active ANSI
    # code page, corrupting the Chinese workspace path.  Keep the exact
    # literal targets but emit UTF-8 with BOM for its parser.
    PS1.write_text("\r\n".join(ps_lines) + "\r\n", encoding="utf-8-sig")
    by_reason = {}
    for r in candidates:
        by_reason[r["reason"]] = by_reason.get(r["reason"], 0) + 1
    lines = [
        "# Cleanup exception: superseded self-generated R1 artifacts\n\n",
        "This is a scoped pre-terminal cleanup. Every listed item is inside this R1 evidence directory, was generated during this audit session, and is absent from the final ledger references. No business source, candidate PDF, sibling/old evidence, or final referenced asset is a target.\n\n",
        f"Planned at: `{datetime.now().astimezone().isoformat(timespec='seconds')}`\n\n",
        "## Scope checks\n\n",
        f"- Final glyph ledger references 114 glyph-card paths; final overlap report references 110 pair-card paths.\n",
        f"- Final low-profile ledger supplies all retained calibration source/native/card paths plus their exact TeX compilation sidecars.\n",
        f"- Planned file count: {len(candidates)}.\n",
    ]
    for reason, count in by_reason.items():
        lines.append(f"- {count}: {reason}.\n")
    lines += [
        "\n## Exact targets before deletion\n\n",
        "| Relative path | Bytes | Last write | SHA-256 before delete | Reason |\n",
        "|---|---:|---|---|---|\n",
    ]
    for r in candidates:
        lines.append(f"| `{r['relative_path']}` | {r['bytes']} | {r['last_write_local']} | `{r['sha256_before_delete']}` | {r['reason']} |\n")
    lines += [
        "\n## Exact deletion method\n\n",
        "`CLEANUP_EXECUTED_EXACT.ps1` contains one `Remove-Item -LiteralPath '<absolute path>' -Force` command per row, with no wildcard, recursion, path variable, or computed target. It is executed in one PowerShell session. This report is then verified before terminal/manifest.\n",
    ]
    REPORT.write_text("".join(lines), encoding="utf-8")


def verify():
    rows = load(TARGETS_CSV)
    survivors = [r["relative_path"] for r in rows if (OUT / r["relative_path"]).exists()]
    expected = expected_files()
    missing_references = sorted(str(p.relative_to(OUT)) for p in expected if not p.exists())
    remaining_unreferenced = plan_targets()
    with REPORT.open("a", encoding="utf-8") as f:
        f.write("\n## Post-delete verification\n\n")
        f.write(f"- Verified at: `{datetime.now().astimezone().isoformat(timespec='seconds')}`.\n")
        f.write(f"- Listed targets still present: {len(survivors)} ({', '.join(survivors) if survivors else 'none'}).\n")
        f.write(f"- Missing current-ledger references: {len(missing_references)} ({', '.join(missing_references) if missing_references else 'none'}).\n")
        f.write(f"- Remaining stale candidates in the four controlled generated folders: {len(remaining_unreferenced)}.\n")
        f.write("- Result: PASS only when all three counts are zero.\n")
    if survivors or missing_references or remaining_unreferenced:
        raise SystemExit(2)
    print("cleanup verification PASS: no targets survive; no referenced artifact missing; no stale candidates remain")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--plan", action="store_true")
    p.add_argument("--verify", action="store_true")
    args = p.parse_args()
    if args.plan == args.verify:
        raise SystemExit("choose exactly one of --plan or --verify")
    if args.plan:
        items = plan_targets()
        write_plan(items)
        print(f"planned {len(items)} literal cleanup targets")
    else:
        verify()
